version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-guidance-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zhuq8yclax89"
s3_prefix = "sam-guidance-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

